environment               = "prod"
monthly_budget_limit      = 1000
enable_vpc_endpoints      = true
max_session_duration      = 3600
secret_rotation_days      = 30
bedrock_model_ids         = ["anthropic.claude-opus-4-7", "anthropic.claude-sonnet-4-20250514", "anthropic.claude-3-5-haiku-20241022", "anthropic.claude-3-opus-20240229"]
alert_emails              = ["prod-alerts@example.com", "oncall@example.com"]
cloudtrail_retention_days = 365
alarm_error_threshold     = 3
